Minor bugfix. Include link to ssdownload.

diff --git a/assets/simplesecrets b/assets/simplesecrets
--- a/assets/simplesecrets
+++ b/assets/simplesecrets
@@ -1,6 +1,8 @@
 #!/bin/bash
 # PASS=password123 ; cat myfile | simplesecrets 
 
+function command_exists { command -v "$1" >/dev/null 2>&1 ; }
+
 if [ ! -e /config/s3 ]; then
   echo "Must call simplesecrets-config first."
   exit 1
@@ -37,7 +39,7 @@ function putS3
   aws_path=$3
   bucket="${BUCKET}"
   date="$(LC_ALL=C date -u +"%a, %d %b %Y %X %z")"
-  acl="x-amz-acl:public-read"
+  md5="$(openssl md5 -binary < "$path/$file" | base64)"
   content_type='application/x-compressed-tar'
   string="PUT\n\n$content_type\n$date\n/$bucket$aws_path$file"
   signature=$(echo -en "${string}" | openssl sha1 -hmac "${S3SECRET}" -binary | base64)
@@ -46,7 +48,13 @@ function putS3
     -H "Date: $date" \
     -H "Content-Type: $content_type" \
     -H "Authorization: AWS ${S3KEY}:$signature" \
+    -H "Content-MD5: $md5" \
     "https://$bucket.s3.amazonaws.com$aws_path$file"
+    
+  if [ $? -ne 0 ]; then
+     echo "Upload failed!"
+     exit 1
+  fi
 }
 
 #-------------------------------------------------------------------------------
@@ -55,6 +63,11 @@ function putS3
 
 # string is null test
 if [ -z "${PASS}" ]; then showusage ; fi
+
+COMMANDS=(gpg openssl md5sum)
+for CMD in "${COMMANDS[@]}"; do
+  if ! command_exists "${CMD}" ; then echo "${CMD} is required" ; exit 1 ; fi
+done
 
 echo "Reading file from stdin..."
 cat > /tmp/file
