Bug fixing gpg

diff --git a/assets/simplesecrets b/assets/simplesecrets
--- a/assets/simplesecrets
+++ b/assets/simplesecrets
@@ -38,20 +38,18 @@ EOF
 function putS3
 {
   path=$1
-  file=$2
-  aws_path=$3
-  bucket="${BUCKET}"
+  aws_path=$2
   date="$(LC_ALL=C date -u +"%a, %d %b %Y %X %z")"
-  md5="$(openssl md5 -binary < "$path/$file" | base64)"
+  md5="$(openssl md5 -binary < "${path}" | base64)"
   content_type='application/x-compressed-tar'
-  string="PUT\n\n${content_type}\n${date}\n/${bucket}${aws_path}${file}"
+  string="PUT\n\n${content_type}\n${date}\n/${BUCKET}${aws_path}"
   signature=$(echo -en "${string}" | openssl sha1 -hmac "${S3SECRET}" -binary | base64)
-  curl -X PUT -T "${path}/${file}" \
-    -H "Host: ${bucket}.s3.amazonaws.com" \
+  curl -X PUT -T "${path}" \
+    -H "Host: ${BUCKET}.s3.amazonaws.com" \
     -H "Date: ${date}" \
     -H "Content-Type: ${content_type}" \
     -H "Authorization: AWS ${S3KEY}:${signature}" \
-    "https://${bucket}.s3.amazonaws.com${aws_path}${file}"
+    "https://${BUCKET}.s3.amazonaws.com${aws_path}"
     
   if [ $? -ne 0 ]; then
      echo "Upload failed!"
@@ -69,7 +67,14 @@ function dogpg {
       exit 1
    fi
    }
-
+# ungpg INPUT PASSPHRASE
+function ungpg { 
+   gpg --yes --batch --passphrase="$2" "$1" > /dev/null 2>&1 ;
+   if [ ! -e "${1%.*}" ]; then
+      echo "Decyption failed - no output ${1%.*}. Passphrase or hash likely incorrect."
+      exit 1
+   fi
+   }
 
 #-------------------------------------------------------------------------------
 
@@ -96,18 +101,18 @@ mkdir /root/.gnupg ; touch /root/.gnupg/gpg.conf
 dogpg "$BASEFILE" "${MD5}"
 dogpg "${BASEFILE}.gpg" "$PASS"
 
-mv "${BASEFILE}.gpg.gpg" "/tmp/${NAME}"
-
-putS3 "/tmp" "${NAME}" "/simplesecrets/"
+putS3 "${BASEFILE}.gpg.gpg" "/simplesecrets/${NAME}"
 
 # confirm file is correct.
-echo "PASS=${PASS} /usr/local/bin/ssdownload ${BUCKET} ${MD5} ${NAME}"
-PASS="${PASS}" /usr/local/bin/ssdownload "${BUCKET}" "${MD5}" "${NAME}" > "$BASEFILE.new"
+#echo "PASS=${PASS} /usr/local/bin/ssdownload ${BUCKET} ${MD5} ${NAME}"
+PASS="$PASS" /usr/local/bin/ssdownload "$BUCKET" "${MD5}" "$NAME" > "${BASEFILE}new.gpg.gpg"
+
 if [ $? -ne 0 ]; then 
-   echo "Validation failed! Download/decryption failed."
-   exit 1
+    echo "Validation failed! Download/decryption failed."
+    exit 1
 fi
-diff "$BASEFILE.new" "$BASEFILE" >/dev/null 2>&1
+
+diff "${BASEFILE}new" "$BASEFILE" >/dev/null 2>&1
 if [ $? -ne 0 ]; then 
    echo "Validation failed! Files differ."
    exit 1
